# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'query_user.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 330)
        MainWindow.setMinimumSize(QtCore.QSize(800, 330))
        MainWindow.setMaximumSize(QtCore.QSize(800, 330))
        font = QtGui.QFont()
        font.setFamily("Fira Code Medium")
        MainWindow.setFont(font)
        MainWindow.setDocumentMode(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(220, 0, 581, 291))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Code Medium")
        font.setPointSize(8)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 201, 271))
        self.groupBox.setObjectName("groupBox")
        self.query_user = QtWidgets.QPushButton(self.groupBox)
        self.query_user.setGeometry(QtCore.QRect(100, 240, 91, 20))
        self.query_user.setObjectName("query_user")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 171, 61))
        self.label_4.setObjectName("label_4")
        self.export_query = QtWidgets.QPushButton(self.groupBox)
        self.export_query.setGeometry(QtCore.QRect(10, 240, 81, 19))
        self.export_query.setObjectName("export_query")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 76, 181, 157))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.first_name_field = QtWidgets.QLineEdit(self.widget)
        self.first_name_field.setObjectName("first_name_field")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.first_name_field)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.last_name_field = QtWidgets.QLineEdit(self.widget)
        self.last_name_field.setObjectName("last_name_field")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.last_name_field)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.email_field = QtWidgets.QLineEdit(self.widget)
        self.email_field.setObjectName("email_field")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.email_field)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.member_since_field = QtWidgets.QDateEdit(self.widget)
        self.member_since_field.setProperty("showGroupSeparator", True)
        self.member_since_field.setCalendarPopup(True)
        self.member_since_field.setObjectName("member_since_field")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.member_since_field)
        self.groupBox.raise_()
        self.tableWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menuBar.setObjectName("menuBar")
        self.menuOptions = QtWidgets.QMenu(self.menuBar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionLogout = QtWidgets.QAction(MainWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuOptions.addAction(self.actionLogout)
        self.menuOptions.addAction(self.actionExit)
        self.menuBar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.first_name_field, self.last_name_field)
        MainWindow.setTabOrder(self.last_name_field, self.email_field)
        MainWindow.setTabOrder(self.email_field, self.member_since_field)
        MainWindow.setTabOrder(self.member_since_field, self.tableWidget)
        MainWindow.setTabOrder(self.tableWidget, self.export_query)
        MainWindow.setTabOrder(self.export_query, self.query_user)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "User Query"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "First Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Last Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "EMail"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Member Number"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Status"))
        self.groupBox.setTitle(_translate("MainWindow", "Query Parameters"))
        self.query_user.setText(_translate("MainWindow", "Query"))
        self.label_4.setText(_translate("MainWindow", "The query is set as:\n"
"(fieldAttribute=textEntered*).\n"
"You may enter the first part of\n"
"any parameter"))
        self.export_query.setText(_translate("MainWindow", "Export"))
        self.label.setText(_translate("MainWindow", "First Name"))
        self.label_2.setText(_translate("MainWindow", "Last Name"))
        self.label_3.setText(_translate("MainWindow", "Email"))
        self.label_5.setText(_translate("MainWindow", "Member Since"))
        self.member_since_field.setDisplayFormat(_translate("MainWindow", "MM/dd/yyyy"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionLogout.setText(_translate("MainWindow", "Logout"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

